include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    cancel_subscriptions: true
    close_sinks: true
    unnecessary_statements: true